# Generated by Django 2.0.4 on 2018-04-28 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='OtherPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('firstProblem', models.IntegerField()),
                ('lastProblem', models.IntegerField()),
                ('firstProblemSubProblems', models.CharField(blank=True, help_text='This is for if the problem range starts with a sub like 15a', max_length=5)),
                ('lastProblemSubProblems', models.CharField(blank=True, help_text='This is for if the problem range ends with a sub like 15b', max_length=5)),
                ('chapterPacket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packets.ChapterPacket')),
                ('otherPacket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packets.OtherPacket')),
            ],
            options={
                'ordering': ['firstProblem'],
            },
        ),
    ]
