# Generated by Django 2.0.4 on 2018-04-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0002_auto_20180428_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterpacket',
            name='id',
        ),
        migrations.AlterField(
            model_name='chapterpacket',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
