# Generated by Django 2.0.4 on 2018-04-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0003_auto_20180429_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterpacket',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chapterpacket',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='otherpacket',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
