# Generated by Django 2.0.4 on 2018-04-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0005_auto_20180429_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterpacket',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chapterpacket',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='otherpacket',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
