# Generated by Django 2.0.4 on 2018-05-12 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0006_auto_20180429_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapterpacket',
            options={},
        ),
        migrations.RemoveField(
            model_name='chapterpacket',
            name='number',
        ),
    ]
